import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import '../../models/yust_file.dart';
import '../../services/yust_file_access_service_interface.dart';

part 'yust_file_access_grant.g.dart';

/// Access grant which shows the client how to access what files.
///
/// This grant has to be generated by the backend and passed to the client.
/// In a typical setup, the backend should send a valid duration or timestamp with that
/// so the client can automatically renew the grants via e.g. an API call to the backend.
///
/// This has to be done in application logic and is not a part of yust.
///
/// An example grant usage or process flow could look like this:
///
/// The client has access to environment1 and to environment2.
/// Once the client logs in, it gets a list of grants and there valid duration from the backend.
/// ```
/// Duration: 1 hour
/// Grant 1:
///   pathPrefix: 'environment1/'
///   originalSignedUrlPart: 'URLPrefix=123&Expires=123&KeyName=123&Signature=123'
///   thumbnailSignedUrlPart: 'URLPrefix=123&Expires=123&KeyName=123&Signature=123'
/// Grant 2:
///   pathPrefix: 'environment2/'
///   originalSignedUrlPart: 'URLPrefix=123&Expires=123&KeyName=123&Signature=123'
///   thumbnailSignedUrlPart: 'URLPrefix=123&Expires=123&KeyName=123&Signature=123'
/// ```
///
/// The client stores this in local state and now knows that any files for environment1
/// can be accessed by appending the [originalSignedUrlPart] to the file url.
///
/// If the client uses YustFiles, the local grants can be kept in sync with yust via the [IYustFileAccessService.setGrants] function
/// which enables the client to use [YustFile.getOriginalUrl] and [YustFile.getThumbnailUrl] to get the correct urls for the files.
///
/// The client must implement its own refreshing logic to renew the grants when they are about to expire.
@JsonSerializable()
@immutable
class YustFileAccessGrant {
  const YustFileAccessGrant({
    required this.pathPrefix,
    required this.originalSignedUrlPart,
    required this.thumbnailSignedUrlPart,
  });

  /// Creates a new file access grant from a JSON map.
  factory YustFileAccessGrant.fromJson(Map<String, dynamic> json) =>
      _$YustFileAccessGrantFromJson(json);

  /// The path prefix of the grant.
  ///
  /// This is used by the client to determine which grant to use for a given file.
  /// The client will check if the file path starts with the path prefix of any available grant.
  /// If so, the client will use the [originalSignedUrlPart] or [thumbnailSignedUrlPart] to load that file.
  ///
  /// This prefix should normally end with a trailing slash.
  /// - 'AE19FQG/' will allow access to all files in the 'AE19FQG' folder.
  /// - 'user123' will allow access to all files in the 'user123' folder but also
  /// to all files or folders which start with 'user123'. For example 'user123-picture.jpeg' and 'user123-videos/video.mp4'.
  ///
  /// The backend has to ensure that the given [originalSignedUrlPart] and [thumbnailSignedUrlPart] are valid for the given [pathPrefix].
  /// The client should only determine the correct grant and use its signed URL parts.
  final String pathPrefix;

  /// The signed URL part the client should append to the url to load original files.
  ///
  /// Example value could look like this: `URLPrefix=123&Expires=123&KeyName=123&Signature=123`
  ///
  /// The client has to decide whether to append the query string with ? or &.
  final String originalSignedUrlPart;

  /// The signed URL part the client should append to the url to load thumbnail files.
  ///
  /// Example value could look like this: `URLPrefix=123&Expires=123&KeyName=123&Signature=123`
  ///
  /// The client has to decide whether to append the query string with ? or &.
  final String thumbnailSignedUrlPart;

  /// Converts the file access grant to a JSON map.
  Map<String, dynamic> toJson() => _$YustFileAccessGrantToJson(this);

  @override
  bool operator ==(Object other) =>
      other is YustFileAccessGrant &&
      pathPrefix == other.pathPrefix &&
      originalSignedUrlPart == other.originalSignedUrlPart &&
      thumbnailSignedUrlPart == other.thumbnailSignedUrlPart;

  @override
  int get hashCode =>
      Object.hash(pathPrefix, originalSignedUrlPart, thumbnailSignedUrlPart);
}
