ignorePaths:
- package-lock.json
- node_modules
- vscode-extension
- ".git/objects"
- ".gitignore"
- ".vscode"
- ".vscode-insiders"
- ".cspell.json"
dictionaryDefinitions:
- name: EN
  description: More english words. (not included in cspell-dict-en-us)
  path: "../univelop/.dictionaries/en.txt"
- name: Misc
  description: Abbreviations, Names, etc.
  path: "../univelop/.dictionaries/misc.txt"
language: en,en-US
dictionaries:
- EN
- Misc
